version: "4"
services:
  backend:
    build: ./Backend
    ports:
      - "5000:4000"
    volumes:
      - ./backend:/app
    networks:
      - livraison-marhaba-net
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - livraison-marhaba-net
networks:
  livraison-marhaba-net:
    external: true