version: "4.14"
services:
  mongodb:
    image: "mongo"
    networks:
      - livraison-marhaba-net
    volumes:
      - data:/data/db
  backend:
    build: ./Backend
    ports:
      - "4000:4000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - livraison-marhaba-net
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - livraison-marhaba-net
volumes:
  data:
  logs:
networks:
  livraison-marhaba-net:
    external: true