name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install jest
        run: cd Backend/ && npm i jest
        
      - name: run test
        run: npm test

